### ISSUE TITLE
Outputs - Grouping replies and Generating json files

### ISSUE THREAD

**Issue by aberja** [gryf/slack-backup#7]
1. Is there a way to group the replies with the original post and note them as replies?  Currently it appears that the replies are are treated as regular posts and filed chronologically.

2. Have you considered providing a second alternative to the generate function? I like the text option as it makes it easy for searching, but I would also like the ability to view the output using: https://github.com/mcoster/slack-export-viewer  This requires the output in json files.

**Comment by gryf** [comment]
1. There is no support for threads in slack-backup - it was introduced like a year ago AFAIR and I had no motivation for providing support for it, as most of the conversations on slack teams I'm member of, are "irc style", so threadless :)
2. I didn't consider any other output, since I simply don't need it. If you find any particular format useful, you can craft it by yourself and provide pull request :)
